package com.a1kesamose.bunksta.Object;

public class Timetable
{
    public long TIMETABLE_ID;
    public long TIMETABLE_COURSE_ID;
    public String TIMETABLE_COURSE_NAME;
    public String TIMETABLE_COURSE_COLOR;
    public int TIMETABLE_DAY_OF_WEEK;
    public int TIMETABLE_START_HOUR;
    public int TIMETABLE_START_MINUTE;
    public int TIMETABLE_END_HOUR;
    public int TIMETABLE_END_MINUTE;

    public Timetable()
    {
        TIMETABLE_ID = 0;
        TIMETABLE_COURSE_ID = 0;
        TIMETABLE_COURSE_NAME = "";
        TIMETABLE_COURSE_COLOR = "";
        TIMETABLE_DAY_OF_WEEK = 0;
        TIMETABLE_START_HOUR = 0;
        TIMETABLE_START_MINUTE = 0;
        TIMETABLE_END_HOUR = 0;
        TIMETABLE_END_MINUTE = 0;
    }

    public Timetable(long TIMETABLE_ID, long TIMETABLE_COURSE_ID, String TIMETABLE_COURSE_NAME, String TIMETABLE_COURSE_COLOR, int TIMETABLE_DAY_OF_WEEK, int TIMETABLE_START_HOUR, int TIMETABLE_START_MINUTE, int TIMETABLE_END_HOUR, int TIMETABLE_END_MINUTE)
    {
        this.TIMETABLE_ID = TIMETABLE_ID;
        this.TIMETABLE_COURSE_ID = TIMETABLE_COURSE_ID;
        this.TIMETABLE_COURSE_NAME = TIMETABLE_COURSE_NAME;
        this.TIMETABLE_COURSE_COLOR = TIMETABLE_COURSE_COLOR;
        this.TIMETABLE_DAY_OF_WEEK = TIMETABLE_DAY_OF_WEEK;
        this.TIMETABLE_START_HOUR = TIMETABLE_START_HOUR;
        this.TIMETABLE_START_MINUTE = TIMETABLE_START_MINUTE;
        this.TIMETABLE_END_HOUR = TIMETABLE_END_HOUR;
        this.TIMETABLE_END_MINUTE = TIMETABLE_END_MINUTE;
    }
}
